- hosts: "localhost"
  connection: "local"
  gather_facts: false

  tasks:
    - name: create a drupal web stack
      cloudformation:
        stack_name: "Drupal-Webserver-CloudFront-Stack-CallahanRob"
        state: "present"
        region: "us-east-1"
        aws_access_key: "AKIAV2ISBBIM7ZY6DFOF"
        aws_secret_key: "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"
        template: drupal.json
        template_parameters:
          AutoScalingNotificationEmail: "robtcallahan@aol.com"
          AvailabilityZones: "us-east-1a,us-east-1b"
          BastionAMIOS: "Amazon-Linux-HVM"
          BastionInstanceType: "t2.micro"
          CloudFrontAlias: "cdn.candidate-syumtueibj.com"
          CloudFrontEnable: "true"
          CloudFrontPriceClass: "use-all-edge-locations"
          DBAutoMinorVersionUpgrade: "true"
          DBBackupRetentionPeriod: 7
          DBInstanceClass: "db.t2.small"
          DBMasterUserPassword: "dbadmin1234"
          DBMasterUsername: "dbadmin"
          DBMultiAZ: "true"
          DrupalDbName: "drupaldb"
          DrupalDbPassword: "drupal1234"
          DrupalDbUsername: "drupal"
          DrupalSiteAdminEmail: "robtcallahan@aol.com"
          DrupalSiteAdminPassword: "admin1234"
          DrupalSiteAdminUsername: "admin"
          DrupalSiteDomain: "candidate-syumtueibj.com"
          DrupalSiteName: "My Site"
          DrupalVersion: 7
          ElastiCacheAutoMinorVersionUpgrade: "true"
          ElastiCacheEnable: "true"
          ElastiCacheNodeType: "cache.t2.micro"
          ElastiCacheNumberOfNodes: 2
          KeyPair: "Candidate-sYumtuEiBJ"
          PhpVersion: "php71"
          PrivateSubnet1CIDR: "10.0.0.0/19"
          PrivateSubnet2CIDR: "10.0.32.0/19"
          PublicSubnet1CIDR: "10.0.128.0/20"
          PublicSubnet2CIDR: "10.0.144.0/20"
          QSS3BucketName: "aws-quickstart"
          QSS3KeyPrefix: "quickstart-drupal/"
          RemoteAccessCIDR: "73.40.5.0/24"
          Route53HostedZoneId: "Z4Q92YEPDCMIC"
          SSLCertificateId: ""
          VPCCIDR: "10.0.0.0/16"
          WebServerDesiredCapacity: 2
          WebServerInstanceType: "t2.micro"
          WebServerMaxSize: 12
          WebServerMinSize: 1
